version: "3.7"
services: 
  db: 
    image: postgres 
    environment: 
      POSTGRES_PASSWORD: " "
      POSTGRES_USER: postgres
      POSTGRES_DB: adb_test
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - '5432:5432'
  web: 
      image: node
      depends_on:
        - db
      ports: 
        - "4000:4000"
